## -*- encoding: utf-8 -*-
## This file (conics-test.sagetex.sage) was *autogenerated* from conics-test.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('conics-test', version='2021/10/16 v3.6', version_check=True)
_st_.current_tex_line = 40
_st_.blockbegin()
try:
 x,y = var('x','y')
 
 def p1(f, xmin=-10, ymin=-10, xmax = 10, ymax = 10):
   c = 10
   xrange = list(range(xmin,xmax+1,2))
   yrange = list(range(ymin,ymax+1,2))
   p=implicit_plot(f,(xmin,xmax),(ymin,ymax),
 linewidth=4,fill=False,axes=True,gridlines=True,frame=False,ticks=[xrange,yrange],fontsize=12)
   return(p)
 
 def hyperbola(a=1,b=1,h=0,k=0,vertical=False):
   z = p1((x-h)^2/a^2-(y-k)^2/b^2 - 1)
   z = z+ plot(b/a*(x-h)+k,(-10,10),color="red",linestyle="dashed")
   z = z+ plot(-b/a*(x-h)+k,(-10,10),color="red",linestyle="dashed")
   z.set_axes_range(-10,10,-10,10)
   return z
 
 def ellipse(a=1,b=1,h=0,k=0):
   z = p1((x-h)^2/a^2+(y-k)^2/b^2 - 1)
   z.set_axes_range(-10,10,-10,10)
   return z
 
 def parabola_v(p=1,h=0,k=0):
   z = p1((x-h)^2 - 4*p*(y-k))
   z = z + point((h,k+p),size=120, rgbcolor='blue')
   z.set_axes_range(-10,10,-10,10)
   return z
 
 def parabola_h(p=1,h=0,k=0):
   z = p1((y-k)^2 - 4*p*(x-h))
   z = z + point((h+p,k),size=120, rgbcolor='blue')
   z.set_axes_range(-10,10,-10,10)
   return z
except:
 _st_.goboom(74)
_st_.blockend()
try:
 _st_.current_tex_line = 97
 _st_.plot(0, format='notprovided', _p_=hyperbola(3,2,3,-4))
except:
 _st_.goboom(97)
try:
 _st_.current_tex_line = 98
 _st_.plot(1, format='notprovided', _p_=hyperbola(3,2,-3,-4))
except:
 _st_.goboom(98)
try:
 _st_.current_tex_line = 99
 _st_.plot(2, format='notprovided', _p_=hyperbola(3,2,3,4))
except:
 _st_.goboom(99)
try:
 _st_.current_tex_line = 101
 _st_.plot(3, format='notprovided', _p_=hyperbola(2,3,3,4))
except:
 _st_.goboom(101)
try:
 _st_.current_tex_line = 102
 _st_.plot(4, format='notprovided', _p_=hyperbola(2,3,3,4))
except:
 _st_.goboom(102)
try:
 _st_.current_tex_line = 103
 _st_.plot(5, format='notprovided', _p_=hyperbola(2,3,0,0))
except:
 _st_.goboom(103)
try:
 _st_.current_tex_line = 109
 _st_.plot(6, format='notprovided', _p_=ellipse(2,3,2,-4))
except:
 _st_.goboom(109)
try:
 _st_.current_tex_line = 110
 _st_.plot(7, format='notprovided', _p_=ellipse(2,3,-2,-4))
except:
 _st_.goboom(110)
try:
 _st_.current_tex_line = 111
 _st_.plot(8, format='notprovided', _p_=ellipse(2,3,2,4))
except:
 _st_.goboom(111)
try:
 _st_.current_tex_line = 113
 _st_.plot(9, format='notprovided', _p_=ellipse(3,4,2,-4))
except:
 _st_.goboom(113)
try:
 _st_.current_tex_line = 114
 _st_.plot(10, format='notprovided', _p_=ellipse(3,2,2,-4))
except:
 _st_.goboom(114)
try:
 _st_.current_tex_line = 115
 _st_.plot(11, format='notprovided', _p_=ellipse(4,9,2,-4))
except:
 _st_.goboom(115)
try:
 _st_.current_tex_line = 123
 _st_.plot(12, format='notprovided', _p_=parabola_h(3,2,4))
except:
 _st_.goboom(123)
try:
 _st_.current_tex_line = 124
 _st_.plot(13, format='notprovided', _p_=parabola_h(-6,2,4))
except:
 _st_.goboom(124)
try:
 _st_.current_tex_line = 125
 _st_.plot(14, format='notprovided', _p_=parabola_h(3,4,2))
except:
 _st_.goboom(125)
try:
 _st_.current_tex_line = 127
 _st_.plot(15, format='notprovided', _p_=parabola_h(6,2,4))
except:
 _st_.goboom(127)
try:
 _st_.current_tex_line = 128
 _st_.plot(16, format='notprovided', _p_=parabola_h(1,2,4))
except:
 _st_.goboom(128)
try:
 _st_.current_tex_line = 129
 _st_.plot(17, format='notprovided', _p_=parabola_h(-6,4,2))
except:
 _st_.goboom(129)
try:
 _st_.current_tex_line = 143
 _st_.inline(0, latex((x-0)^2))
except:
 _st_.goboom(143)
try:
 _st_.current_tex_line = 143
 _st_.inline(1, latex(3^2))
except:
 _st_.goboom(143)
try:
 _st_.current_tex_line = 143
 _st_.inline(2, latex((y-2)^2))
except:
 _st_.goboom(143)
try:
 _st_.current_tex_line = 143
 _st_.inline(3, latex(sqrt(7)^2))
except:
 _st_.goboom(143)
try:
 _st_.current_tex_line = 155
 _st_.inline(4, latex((x--3)^2))
except:
 _st_.goboom(155)
try:
 _st_.current_tex_line = 155
 _st_.inline(5, latex(10^2))
except:
 _st_.goboom(155)
try:
 _st_.current_tex_line = 155
 _st_.inline(6, latex((y--2)^2))
except:
 _st_.goboom(155)
try:
 _st_.current_tex_line = 155
 _st_.inline(7, latex(6^2))
except:
 _st_.goboom(155)
try:
 _st_.current_tex_line = 156
 _st_.inline(8, latex((x--3)^2))
except:
 _st_.goboom(156)
try:
 _st_.current_tex_line = 156
 _st_.inline(9, latex(8^2))
except:
 _st_.goboom(156)
try:
 _st_.current_tex_line = 156
 _st_.inline(10, latex((y-2)^2))
except:
 _st_.goboom(156)
try:
 _st_.current_tex_line = 156
 _st_.inline(11, latex(10^2))
except:
 _st_.goboom(156)
try:
 _st_.current_tex_line = 157
 _st_.inline(12, latex((x-3)^2))
except:
 _st_.goboom(157)
try:
 _st_.current_tex_line = 157
 _st_.inline(13, latex(10^2))
except:
 _st_.goboom(157)
try:
 _st_.current_tex_line = 157
 _st_.inline(14, latex((y--2)^2))
except:
 _st_.goboom(157)
try:
 _st_.current_tex_line = 157
 _st_.inline(15, latex(6^2))
except:
 _st_.goboom(157)
try:
 _st_.current_tex_line = 158
 _st_.inline(16, latex((x-3)^2))
except:
 _st_.goboom(158)
try:
 _st_.current_tex_line = 158
 _st_.inline(17, latex(6^2))
except:
 _st_.goboom(158)
try:
 _st_.current_tex_line = 158
 _st_.inline(18, latex((y--2)^2))
except:
 _st_.goboom(158)
try:
 _st_.current_tex_line = 158
 _st_.inline(19, latex(8^2))
except:
 _st_.goboom(158)
try:
 _st_.current_tex_line = 165
 _st_.inline(20, latex((x-3)^2))
except:
 _st_.goboom(165)
try:
 _st_.current_tex_line = 165
 _st_.inline(21, latex(4*1/3))
except:
 _st_.goboom(165)
try:
 _st_.current_tex_line = 165
 _st_.inline(22, latex((y--2)))
except:
 _st_.goboom(165)
try:
 _st_.current_tex_line = 166
 _st_.inline(23, latex((x-3)^2))
except:
 _st_.goboom(166)
try:
 _st_.current_tex_line = 166
 _st_.inline(24, latex(4*1/9))
except:
 _st_.goboom(166)
try:
 _st_.current_tex_line = 166
 _st_.inline(25, latex((y--2)))
except:
 _st_.goboom(166)
try:
 _st_.current_tex_line = 167
 _st_.inline(26, latex((x-3)^2))
except:
 _st_.goboom(167)
try:
 _st_.current_tex_line = 167
 _st_.inline(27, latex(4*1))
except:
 _st_.goboom(167)
try:
 _st_.current_tex_line = 167
 _st_.inline(28, latex((y--2)))
except:
 _st_.goboom(167)
try:
 _st_.current_tex_line = 168
 _st_.inline(29, latex((x-3)^2))
except:
 _st_.goboom(168)
try:
 _st_.current_tex_line = 168
 _st_.inline(30, latex(4*3))
except:
 _st_.goboom(168)
try:
 _st_.current_tex_line = 168
 _st_.inline(31, latex((y-2)))
except:
 _st_.goboom(168)
try:
 _st_.current_tex_line = 169
 _st_.inline(32, latex((x--3)^2))
except:
 _st_.goboom(169)
try:
 _st_.current_tex_line = 169
 _st_.inline(33, latex(4*3))
except:
 _st_.goboom(169)
try:
 _st_.current_tex_line = 169
 _st_.inline(34, latex((y--2)))
except:
 _st_.goboom(169)
_st_.endofdoc()
