## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file conics-test.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_33 = Integer(33); _sage_const_10 = Integer(10); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_12 = Integer(12); _sage_const_0 = Integer(0); _sage_const_5 = Integer(5); _sage_const_60 = Integer(60); _sage_const_66 = Integer(66); _sage_const_73 = Integer(73); _sage_const_3 = Integer(3); _sage_const_74 = Integer(74); _sage_const_75 = Integer(75); _sage_const_77 = Integer(77); _sage_const_78 = Integer(78); _sage_const_79 = Integer(79); _sage_const_85 = Integer(85); _sage_const_6 = Integer(6); _sage_const_86 = Integer(86); _sage_const_7 = Integer(7); _sage_const_87 = Integer(87); _sage_const_8 = Integer(8); _sage_const_89 = Integer(89); _sage_const_9 = Integer(9); _sage_const_90 = Integer(90); _sage_const_91 = Integer(91); _sage_const_11 = Integer(11); _sage_const_99 = Integer(99); _sage_const_100 = Integer(100); _sage_const_13 = Integer(13); _sage_const_101 = Integer(101); _sage_const_14 = Integer(14); _sage_const_103 = Integer(103); _sage_const_15 = Integer(15); _sage_const_104 = Integer(104); _sage_const_16 = Integer(16); _sage_const_105 = Integer(105); _sage_const_17 = Integer(17); _sage_const_118 = Integer(118); _sage_const_127 = Integer(127); _sage_const_136 = Integer(136); _sage_const_145 = Integer(145)## This file (conics-test.sagetex.sage) was *autogenerated* from conics-test.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('conics-test', version='2021/10/16 v3.6', version_check=True)
_st_.current_tex_line = _sage_const_33 
_st_.blockbegin()
try:
 x,y = var('x','y')
 
 def p1(f, xmin=-_sage_const_10 , ymin=-_sage_const_10 , xmax = _sage_const_10 , ymax = _sage_const_10 ):
   c = _sage_const_10 
   xrange = list(range(xmin,xmax+_sage_const_1 ,_sage_const_2 ))
   yrange = list(range(ymin,ymax+_sage_const_1 ,_sage_const_2 ))
   p=implicit_plot(f,(xmin,xmax),(ymin,ymax),
 linewidth=_sage_const_4 ,fill=False,axes=True,gridlines=True,frame=False,ticks=[xrange,yrange],fontsize=_sage_const_12 )
   return(p)
 
 def hyperbola(a=_sage_const_1 ,b=_sage_const_1 ,h=_sage_const_0 ,k=_sage_const_0 ,vertical=False):
   z = p1((x-h)**_sage_const_2 /a**_sage_const_2 -(y-k)**_sage_const_2 /b**_sage_const_2  - _sage_const_1 )
   z = z+ plot(b/a*(x-h)+k,(-_sage_const_5 ,_sage_const_5 ),color="gray",linestyle="dashed")
   z = z+ plot(-b/a*(x-h)+k,(-_sage_const_5 ,_sage_const_5 ),color="gray",linestyle="dashed")
   z.set_axes_range(-_sage_const_10 ,_sage_const_10 ,-_sage_const_10 ,_sage_const_10 )
   return z
 
 def ellipse(a=_sage_const_1 ,b=_sage_const_1 ,h=_sage_const_0 ,k=_sage_const_0 ):
   z = p1((x-h)**_sage_const_2 /a**_sage_const_2 +(y-k)**_sage_const_2 /b**_sage_const_2  - _sage_const_1 )
   z.set_axes_range(-_sage_const_10 ,_sage_const_10 ,-_sage_const_10 ,_sage_const_10 )
   return z
 
 def parabola_v(p=_sage_const_1 ,h=_sage_const_0 ,k=_sage_const_0 ):
   z = p1((x-h)**_sage_const_2  - _sage_const_4 *p*(y-k))
   z = z + point((h,k+p),size=_sage_const_60 , rgbcolor='blue')
   z.set_axes_range(-_sage_const_10 ,_sage_const_10 ,-_sage_const_10 ,_sage_const_10 )
   return z
 def parabola_h(p=_sage_const_1 ,h=_sage_const_0 ,k=_sage_const_0 ):
   z = p1((y-k)**_sage_const_2  - _sage_const_4 *p*(x-h))
   z = z + point((h+p,k),size=_sage_const_60 , rgbcolor='blue')
   z.set_axes_range(-_sage_const_10 ,_sage_const_10 ,-_sage_const_10 ,_sage_const_10 )
   return z
except:
 _st_.goboom(_sage_const_66 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_73 
 _st_.plot(_sage_const_0 , format='notprovided', _p_=hyperbola(_sage_const_3 ,_sage_const_2 ,_sage_const_3 ,-_sage_const_4 ))
except:
 _st_.goboom(_sage_const_73 )
try:
 _st_.current_tex_line = _sage_const_74 
 _st_.plot(_sage_const_1 , format='notprovided', _p_=hyperbola(_sage_const_3 ,_sage_const_2 ,-_sage_const_3 ,-_sage_const_4 ))
except:
 _st_.goboom(_sage_const_74 )
try:
 _st_.current_tex_line = _sage_const_75 
 _st_.plot(_sage_const_2 , format='notprovided', _p_=hyperbola(_sage_const_3 ,_sage_const_2 ,_sage_const_3 ,_sage_const_4 ))
except:
 _st_.goboom(_sage_const_75 )
try:
 _st_.current_tex_line = _sage_const_77 
 _st_.plot(_sage_const_3 , format='notprovided', _p_=hyperbola(_sage_const_2 ,_sage_const_3 ,_sage_const_3 ,_sage_const_4 ))
except:
 _st_.goboom(_sage_const_77 )
try:
 _st_.current_tex_line = _sage_const_78 
 _st_.plot(_sage_const_4 , format='notprovided', _p_=hyperbola(_sage_const_2 ,_sage_const_3 ,_sage_const_3 ,_sage_const_4 ))
except:
 _st_.goboom(_sage_const_78 )
try:
 _st_.current_tex_line = _sage_const_79 
 _st_.plot(_sage_const_5 , format='notprovided', _p_=hyperbola(_sage_const_2 ,_sage_const_3 ,_sage_const_0 ,_sage_const_0 ))
except:
 _st_.goboom(_sage_const_79 )
try:
 _st_.current_tex_line = _sage_const_85 
 _st_.plot(_sage_const_6 , format='notprovided', _p_=ellipse(_sage_const_2 ,_sage_const_3 ,_sage_const_2 ,-_sage_const_4 ))
except:
 _st_.goboom(_sage_const_85 )
try:
 _st_.current_tex_line = _sage_const_86 
 _st_.plot(_sage_const_7 , format='notprovided', _p_=ellipse(_sage_const_2 ,_sage_const_3 ,-_sage_const_2 ,-_sage_const_4 ))
except:
 _st_.goboom(_sage_const_86 )
try:
 _st_.current_tex_line = _sage_const_87 
 _st_.plot(_sage_const_8 , format='notprovided', _p_=ellipse(_sage_const_2 ,_sage_const_3 ,_sage_const_2 ,_sage_const_4 ))
except:
 _st_.goboom(_sage_const_87 )
try:
 _st_.current_tex_line = _sage_const_89 
 _st_.plot(_sage_const_9 , format='notprovided', _p_=ellipse(_sage_const_3 ,_sage_const_4 ,_sage_const_2 ,-_sage_const_4 ))
except:
 _st_.goboom(_sage_const_89 )
try:
 _st_.current_tex_line = _sage_const_90 
 _st_.plot(_sage_const_10 , format='notprovided', _p_=ellipse(_sage_const_3 ,_sage_const_2 ,_sage_const_2 ,-_sage_const_4 ))
except:
 _st_.goboom(_sage_const_90 )
try:
 _st_.current_tex_line = _sage_const_91 
 _st_.plot(_sage_const_11 , format='notprovided', _p_=ellipse(_sage_const_4 ,_sage_const_9 ,_sage_const_2 ,-_sage_const_4 ))
except:
 _st_.goboom(_sage_const_91 )
try:
 _st_.current_tex_line = _sage_const_99 
 _st_.plot(_sage_const_12 , format='notprovided', _p_=parabola_h(_sage_const_3 ,_sage_const_2 ,_sage_const_4 ))
except:
 _st_.goboom(_sage_const_99 )
try:
 _st_.current_tex_line = _sage_const_100 
 _st_.plot(_sage_const_13 , format='notprovided', _p_=parabola_h(-_sage_const_6 ,_sage_const_2 ,_sage_const_4 ))
except:
 _st_.goboom(_sage_const_100 )
try:
 _st_.current_tex_line = _sage_const_101 
 _st_.plot(_sage_const_14 , format='notprovided', _p_=parabola_h(_sage_const_3 ,_sage_const_4 ,_sage_const_2 ))
except:
 _st_.goboom(_sage_const_101 )
try:
 _st_.current_tex_line = _sage_const_103 
 _st_.plot(_sage_const_15 , format='notprovided', _p_=parabola_h(_sage_const_6 ,_sage_const_2 ,_sage_const_4 ))
except:
 _st_.goboom(_sage_const_103 )
try:
 _st_.current_tex_line = _sage_const_104 
 _st_.plot(_sage_const_16 , format='notprovided', _p_=parabola_h(_sage_const_1 ,_sage_const_2 ,_sage_const_4 ))
except:
 _st_.goboom(_sage_const_104 )
try:
 _st_.current_tex_line = _sage_const_105 
 _st_.plot(_sage_const_17 , format='notprovided', _p_=parabola_h(-_sage_const_6 ,_sage_const_4 ,_sage_const_2 ))
except:
 _st_.goboom(_sage_const_105 )
try:
 _st_.current_tex_line = _sage_const_118 
 _st_.inline(_sage_const_0 , latex((x-_sage_const_0 )**_sage_const_2 ))
except:
 _st_.goboom(_sage_const_118 )
try:
 _st_.current_tex_line = _sage_const_118 
 _st_.inline(_sage_const_1 , latex(_sage_const_3 **_sage_const_2 ))
except:
 _st_.goboom(_sage_const_118 )
try:
 _st_.current_tex_line = _sage_const_118 
 _st_.inline(_sage_const_2 , latex((y-_sage_const_2 )**_sage_const_2 ))
except:
 _st_.goboom(_sage_const_118 )
try:
 _st_.current_tex_line = _sage_const_118 
 _st_.inline(_sage_const_3 , latex(sqrt(_sage_const_7 )**_sage_const_2 ))
except:
 _st_.goboom(_sage_const_118 )
try:
 _st_.current_tex_line = _sage_const_127 
 _st_.inline(_sage_const_4 , latex((x-_sage_const_0 )**_sage_const_2 ))
except:
 _st_.goboom(_sage_const_127 )
try:
 _st_.current_tex_line = _sage_const_127 
 _st_.inline(_sage_const_5 , latex(_sage_const_3 **_sage_const_2 ))
except:
 _st_.goboom(_sage_const_127 )
try:
 _st_.current_tex_line = _sage_const_127 
 _st_.inline(_sage_const_6 , latex((y-_sage_const_2 )**_sage_const_2 ))
except:
 _st_.goboom(_sage_const_127 )
try:
 _st_.current_tex_line = _sage_const_127 
 _st_.inline(_sage_const_7 , latex(sqrt(_sage_const_7 )**_sage_const_2 ))
except:
 _st_.goboom(_sage_const_127 )
try:
 _st_.current_tex_line = _sage_const_136 
 _st_.inline(_sage_const_8 , latex((x-_sage_const_0 )**_sage_const_2 ))
except:
 _st_.goboom(_sage_const_136 )
try:
 _st_.current_tex_line = _sage_const_136 
 _st_.inline(_sage_const_9 , latex(_sage_const_3 **_sage_const_2 ))
except:
 _st_.goboom(_sage_const_136 )
try:
 _st_.current_tex_line = _sage_const_136 
 _st_.inline(_sage_const_10 , latex((y-_sage_const_2 )**_sage_const_2 ))
except:
 _st_.goboom(_sage_const_136 )
try:
 _st_.current_tex_line = _sage_const_136 
 _st_.inline(_sage_const_11 , latex(sqrt(_sage_const_7 )**_sage_const_2 ))
except:
 _st_.goboom(_sage_const_136 )
try:
 _st_.current_tex_line = _sage_const_145 
 _st_.inline(_sage_const_12 , latex((x-_sage_const_0 )**_sage_const_2 ))
except:
 _st_.goboom(_sage_const_145 )
try:
 _st_.current_tex_line = _sage_const_145 
 _st_.inline(_sage_const_13 , latex(_sage_const_3 **_sage_const_2 ))
except:
 _st_.goboom(_sage_const_145 )
try:
 _st_.current_tex_line = _sage_const_145 
 _st_.inline(_sage_const_14 , latex((y-_sage_const_2 )**_sage_const_2 ))
except:
 _st_.goboom(_sage_const_145 )
try:
 _st_.current_tex_line = _sage_const_145 
 _st_.inline(_sage_const_15 , latex(sqrt(_sage_const_7 )**_sage_const_2 ))
except:
 _st_.goboom(_sage_const_145 )
_st_.endofdoc()

