## -*- encoding: utf-8 -*-
## This file (conics-test.sagetex.sage) was *autogenerated* from conics-test.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('conics-test', version='2021/10/16 v3.6', version_check=True)
_st_.current_tex_line = 33
_st_.blockbegin()
try:
 x,y = var('x','y')
 
 def p1(f, xmin=-5, ymin=-5, xmax = 5, ymax = 5):
   c = 10
   xrange = list(range(xmin,xmax+1))
   yrange = list(range(ymin,ymax+1))
   p=implicit_plot(f,(xmin,xmax),(ymin,ymax),
 linewidth=4,fill=False,axes=True,gridlines=True,frame=False,ticks=[xrange,yrange],fontsize=12)
   return(p)
 
 def hyperbola(a=1,b=1,h=0,k=0,vertical=False):
   z = p1((x-h)^2/a^2-(y-k)^2/b^2 - 1)
   z = z+ plot(b/a*(x-h)+k,(-5,5),color="gray",linestyle="dashed")
   z = z+ plot(-b/a*(x-h)+k,(-5,5),color="gray",linestyle="dashed")
   z.set_axes_range(-5,5,-5,5)
   return z
except:
 _st_.goboom(50)
_st_.blockend()
try:
 _st_.current_tex_line = 57
 _st_.plot(0, format='notprovided', _p_=hyperbola(1,2,1,1))
except:
 _st_.goboom(57)
try:
 _st_.current_tex_line = 58
 _st_.plot(1, format='notprovided', _p_=hyperbola(2,1,1,1))
except:
 _st_.goboom(58)
try:
 _st_.current_tex_line = 60
 _st_.plot(2, format='notprovided', _p_=hyperbola(1,1,-2,1))
except:
 _st_.goboom(60)
try:
 _st_.current_tex_line = 61
 _st_.plot(3, format='notprovided', _p_=hyperbola(1,1,-2,2))
except:
 _st_.goboom(61)
try:
 _st_.current_tex_line = 73
 _st_.inline(0, latex((x-0)^2))
except:
 _st_.goboom(73)
try:
 _st_.current_tex_line = 73
 _st_.inline(1, latex(3^2))
except:
 _st_.goboom(73)
try:
 _st_.current_tex_line = 73
 _st_.inline(2, latex((y-2)^2))
except:
 _st_.goboom(73)
try:
 _st_.current_tex_line = 73
 _st_.inline(3, latex(sqrt(7)^2))
except:
 _st_.goboom(73)
try:
 _st_.current_tex_line = 82
 _st_.inline(4, latex((x-0)^2))
except:
 _st_.goboom(82)
try:
 _st_.current_tex_line = 82
 _st_.inline(5, latex(3^2))
except:
 _st_.goboom(82)
try:
 _st_.current_tex_line = 82
 _st_.inline(6, latex((y-2)^2))
except:
 _st_.goboom(82)
try:
 _st_.current_tex_line = 82
 _st_.inline(7, latex(sqrt(7)^2))
except:
 _st_.goboom(82)
try:
 _st_.current_tex_line = 91
 _st_.inline(8, latex((x-0)^2))
except:
 _st_.goboom(91)
try:
 _st_.current_tex_line = 91
 _st_.inline(9, latex(3^2))
except:
 _st_.goboom(91)
try:
 _st_.current_tex_line = 91
 _st_.inline(10, latex((y-2)^2))
except:
 _st_.goboom(91)
try:
 _st_.current_tex_line = 91
 _st_.inline(11, latex(sqrt(7)^2))
except:
 _st_.goboom(91)
try:
 _st_.current_tex_line = 100
 _st_.inline(12, latex((x-0)^2))
except:
 _st_.goboom(100)
try:
 _st_.current_tex_line = 100
 _st_.inline(13, latex(3^2))
except:
 _st_.goboom(100)
try:
 _st_.current_tex_line = 100
 _st_.inline(14, latex((y-2)^2))
except:
 _st_.goboom(100)
try:
 _st_.current_tex_line = 100
 _st_.inline(15, latex(sqrt(7)^2))
except:
 _st_.goboom(100)
_st_.endofdoc()
