## -*- encoding: utf-8 -*-
## This file (conics-test.sagetex.sage) was *autogenerated* from conics-test.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('conics-test', version='2021/10/16 v3.6', version_check=True)
_st_.current_tex_line = 44
_st_.blockbegin()
try:
 x,y = var('x','y')
 
 def p1(f, xmin=-10, ymin=-10, xmax = 10, ymax = 10):
   c = 10
   xrange = list(range(xmin,xmax+1,2))
   yrange = list(range(ymin,ymax+1,2))
   p=implicit_plot(f,(xmin,xmax),(ymin,ymax),
 linewidth=4,fill=False,axes=True,gridlines=True,frame=False,ticks=[xrange,yrange],fontsize=12)
   return(p)
 
 def hyperbola(a=1,b=1,h=0,k=0,vertical=False):
   z = p1((x-h)^2/a^2-(y-k)^2/b^2 - 1)
   if (vertical):
     z = p1((y-k)^2/b^2-(x-h)^2/a^2 - 1)
   z = z+ plot(b/a*(x-h)+k,(-10,10),color="red",linestyle="dashed")
   z = z+ plot(-b/a*(x-h)+k,(-10,10),color="red",linestyle="dashed")
   z.set_axes_range(-10,10,-10,10)
   return z
 
 def ellipse(a=1,b=1,h=0,k=0):
   z = p1((x-h)^2/a^2+(y-k)^2/b^2 - 1)
   z.set_axes_range(-10,10,-10,10)
   return z
 
 def parabola_v(p=1,h=0,k=0):
   z = p1((x-h)^2 - 4*p*(y-k))
   z = z + point((h,k+p),size=120, rgbcolor='blue')
   z.set_axes_range(-10,10,-10,10)
   return z
 
 def parabola_h(p=1,h=0,k=0):
   z = p1((y-k)^2 - 4*p*(x-h))
   z = z + point((h+p,k),size=120, rgbcolor='blue')
   z.set_axes_range(-10,10,-10,10)
   return z
except:
 _st_.goboom(80)
_st_.blockend()
try:
 _st_.current_tex_line = 106
 _st_.plot(0, format='notprovided', _p_=hyperbola(2,3,3,4))
except:
 _st_.goboom(106)
try:
 _st_.current_tex_line = 107
 _st_.plot(1, format='notprovided', _p_=hyperbola(3,2,3,-4))
except:
 _st_.goboom(107)
try:
 _st_.current_tex_line = 108
 _st_.plot(2, format='notprovided', _p_=hyperbola(2,3,3,-4,true))
except:
 _st_.goboom(108)
try:
 _st_.current_tex_line = 110
 _st_.plot(3, format='notprovided', _p_=hyperbola(3,2,3,4))
except:
 _st_.goboom(110)
try:
 _st_.current_tex_line = 111
 _st_.plot(4, format='notprovided', _p_=hyperbola(2,3,3,-4))
except:
 _st_.goboom(111)
try:
 _st_.current_tex_line = 112
 _st_.plot(5, format='notprovided', _p_=hyperbola(3,2,-3,-4))
except:
 _st_.goboom(112)
try:
 _st_.current_tex_line = 118
 _st_.plot(6, format='notprovided', _p_=ellipse(2,3,2,4))
except:
 _st_.goboom(118)
try:
 _st_.current_tex_line = 119
 _st_.plot(7, format='notprovided', _p_=ellipse(4,9,2,-4))
except:
 _st_.goboom(119)
try:
 _st_.current_tex_line = 120
 _st_.plot(8, format='notprovided', _p_=ellipse(3,2,2,-4))
except:
 _st_.goboom(120)
try:
 _st_.current_tex_line = 122
 _st_.plot(9, format='notprovided', _p_=ellipse(2,3,-2,-4))
except:
 _st_.goboom(122)
try:
 _st_.current_tex_line = 123
 _st_.plot(10, format='notprovided', _p_=ellipse(2,3,2,-4))
except:
 _st_.goboom(123)
try:
 _st_.current_tex_line = 124
 _st_.plot(11, format='notprovided', _p_=ellipse(3,4,2,-4))
except:
 _st_.goboom(124)
try:
 _st_.current_tex_line = 132
 _st_.plot(12, format='notprovided', _p_=parabola_h(3,2,4))
except:
 _st_.goboom(132)
try:
 _st_.current_tex_line = 133
 _st_.plot(13, format='notprovided', _p_=parabola_h(-6,2,4))
except:
 _st_.goboom(133)
try:
 _st_.current_tex_line = 134
 _st_.plot(14, format='notprovided', _p_=parabola_h(-6,4,2))
except:
 _st_.goboom(134)
try:
 _st_.current_tex_line = 136
 _st_.plot(15, format='notprovided', _p_=parabola_h(1,2,4))
except:
 _st_.goboom(136)
try:
 _st_.current_tex_line = 137
 _st_.plot(16, format='notprovided', _p_=parabola_h(6,2,4))
except:
 _st_.goboom(137)
try:
 _st_.current_tex_line = 138
 _st_.plot(17, format='notprovided', _p_=parabola_h(3,4,2))
except:
 _st_.goboom(138)
try:
 _st_.current_tex_line = 153
 _st_.inline(0, latex((x-0)^2))
except:
 _st_.goboom(153)
try:
 _st_.current_tex_line = 153
 _st_.inline(1, latex(3^2))
except:
 _st_.goboom(153)
try:
 _st_.current_tex_line = 153
 _st_.inline(2, latex((y-2)^2))
except:
 _st_.goboom(153)
try:
 _st_.current_tex_line = 153
 _st_.inline(3, latex(sqrt(7)^2))
except:
 _st_.goboom(153)
try:
 _st_.current_tex_line = 182
 _st_.inline(4, latex((x--3)^2))
except:
 _st_.goboom(182)
try:
 _st_.current_tex_line = 182
 _st_.inline(5, latex(4*3))
except:
 _st_.goboom(182)
try:
 _st_.current_tex_line = 182
 _st_.inline(6, latex((y--2)))
except:
 _st_.goboom(182)
try:
 _st_.current_tex_line = 183
 _st_.inline(7, latex((x-3)^2))
except:
 _st_.goboom(183)
try:
 _st_.current_tex_line = 183
 _st_.inline(8, latex(4*3))
except:
 _st_.goboom(183)
try:
 _st_.current_tex_line = 183
 _st_.inline(9, latex((y-2)))
except:
 _st_.goboom(183)
try:
 _st_.current_tex_line = 184
 _st_.inline(10, latex((x-3)^2))
except:
 _st_.goboom(184)
try:
 _st_.current_tex_line = 184
 _st_.inline(11, latex(4*3/4))
except:
 _st_.goboom(184)
try:
 _st_.current_tex_line = 184
 _st_.inline(12, latex((y--2)))
except:
 _st_.goboom(184)
try:
 _st_.current_tex_line = 185
 _st_.inline(13, latex((x-3)^2))
except:
 _st_.goboom(185)
try:
 _st_.current_tex_line = 185
 _st_.inline(14, latex(4*1/9))
except:
 _st_.goboom(185)
try:
 _st_.current_tex_line = 185
 _st_.inline(15, latex((y--2)))
except:
 _st_.goboom(185)
try:
 _st_.current_tex_line = 186
 _st_.inline(16, latex((x-3)^2))
except:
 _st_.goboom(186)
try:
 _st_.current_tex_line = 186
 _st_.inline(17, latex(4*1))
except:
 _st_.goboom(186)
try:
 _st_.current_tex_line = 186
 _st_.inline(18, latex((y--2)))
except:
 _st_.goboom(186)
try:
 _st_.current_tex_line = 205
 _st_.inline(19, latex((x--11)^2))
except:
 _st_.goboom(205)
try:
 _st_.current_tex_line = 205
 _st_.inline(20, latex(14^2))
except:
 _st_.goboom(205)
try:
 _st_.current_tex_line = 205
 _st_.inline(21, latex((y--8)^2))
except:
 _st_.goboom(205)
try:
 _st_.current_tex_line = 205
 _st_.inline(22, latex(13^2))
except:
 _st_.goboom(205)
try:
 _st_.current_tex_line = 206
 _st_.inline(23, latex((x-11)^2))
except:
 _st_.goboom(206)
try:
 _st_.current_tex_line = 206
 _st_.inline(24, latex(14^2))
except:
 _st_.goboom(206)
try:
 _st_.current_tex_line = 206
 _st_.inline(25, latex((y-8)^2))
except:
 _st_.goboom(206)
try:
 _st_.current_tex_line = 206
 _st_.inline(26, latex(13^2))
except:
 _st_.goboom(206)
try:
 _st_.current_tex_line = 207
 _st_.inline(27, latex((x--11)^2))
except:
 _st_.goboom(207)
try:
 _st_.current_tex_line = 207
 _st_.inline(28, latex(13^2))
except:
 _st_.goboom(207)
try:
 _st_.current_tex_line = 207
 _st_.inline(29, latex((y--8)^2))
except:
 _st_.goboom(207)
try:
 _st_.current_tex_line = 207
 _st_.inline(30, latex(14^2))
except:
 _st_.goboom(207)
try:
 _st_.current_tex_line = 208
 _st_.inline(31, latex((x-11)^2))
except:
 _st_.goboom(208)
try:
 _st_.current_tex_line = 208
 _st_.inline(32, latex(13^2))
except:
 _st_.goboom(208)
try:
 _st_.current_tex_line = 208
 _st_.inline(33, latex((y-8)^2))
except:
 _st_.goboom(208)
try:
 _st_.current_tex_line = 208
 _st_.inline(34, latex(14^2))
except:
 _st_.goboom(208)
_st_.endofdoc()
