## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file conics-test.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_30 = Integer(30); _sage_const_5 = Integer(5); _sage_const_10 = Integer(10); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4); _sage_const_12 = Integer(12); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_47 = Integer(47); _sage_const_54 = Integer(54); _sage_const_55 = Integer(55); _sage_const_56 = Integer(56); _sage_const_57 = Integer(57); _sage_const_3 = Integer(3); _sage_const_70 = Integer(70); _sage_const_7 = Integer(7); _sage_const_80 = Integer(80); _sage_const_6 = Integer(6); _sage_const_90 = Integer(90); _sage_const_8 = Integer(8); _sage_const_9 = Integer(9); _sage_const_11 = Integer(11); _sage_const_100 = Integer(100); _sage_const_13 = Integer(13); _sage_const_14 = Integer(14); _sage_const_15 = Integer(15)## This file (conics-test.sagetex.sage) was *autogenerated* from conics-test.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('conics-test', version='2021/10/16 v3.6', version_check=True)
_st_.current_tex_line = _sage_const_30 
_st_.blockbegin()
try:
 x,y = var('x','y')
 
 def p1(f, xmin=-_sage_const_5 , ymin=-_sage_const_5 , xmax = _sage_const_5 , ymax = _sage_const_5 ):
   c = _sage_const_10 
   xrange = list(range(xmin,xmax+_sage_const_1 ))
   yrange = list(range(ymin,ymax+_sage_const_1 ))
   p=implicit_plot(f,(xmin,xmax),(ymin,ymax),
 linewidth=_sage_const_4 ,fill=False,axes=True,gridlines=True,frame=False,ticks=[xrange,yrange],fontsize=_sage_const_12 )
   return(p)
 
 def hyperbola(a=_sage_const_1 ,b=_sage_const_1 ,h=_sage_const_0 ,k=_sage_const_0 ,vertical=False):
   z = p1((x-h)**_sage_const_2 /a**_sage_const_2 -(y-k)**_sage_const_2 /b**_sage_const_2  - _sage_const_1 )
   z = z+ plot(b/a*(x-h)+k,(-_sage_const_5 ,_sage_const_5 ),color="gray",linestyle="dashed")
   z = z+ plot(-b/a*(x-h)+k,(-_sage_const_5 ,_sage_const_5 ),color="gray",linestyle="dashed")
   z.set_axes_range(-_sage_const_5 ,_sage_const_5 ,-_sage_const_5 ,_sage_const_5 )
   return z
except:
 _st_.goboom(_sage_const_47 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_54 
 _st_.plot(_sage_const_0 , format='notprovided', _p_=hyperbola(_sage_const_1 ,_sage_const_2 ,_sage_const_1 ,_sage_const_1 ))
except:
 _st_.goboom(_sage_const_54 )
try:
 _st_.current_tex_line = _sage_const_55 
 _st_.plot(_sage_const_1 , format='notprovided', _p_=hyperbola(_sage_const_2 ,_sage_const_1 ,_sage_const_1 ,_sage_const_1 ))
except:
 _st_.goboom(_sage_const_55 )
try:
 _st_.current_tex_line = _sage_const_56 
 _st_.plot(_sage_const_2 , format='notprovided', _p_=hyperbola(_sage_const_1 ,_sage_const_1 ,-_sage_const_2 ,_sage_const_1 ))
except:
 _st_.goboom(_sage_const_56 )
try:
 _st_.current_tex_line = _sage_const_57 
 _st_.plot(_sage_const_3 , format='notprovided', _p_=hyperbola(_sage_const_1 ,_sage_const_1 ,-_sage_const_2 ,_sage_const_2 ))
except:
 _st_.goboom(_sage_const_57 )
try:
 _st_.current_tex_line = _sage_const_70 
 _st_.inline(_sage_const_0 , latex((x-_sage_const_0 )**_sage_const_2 ))
except:
 _st_.goboom(_sage_const_70 )
try:
 _st_.current_tex_line = _sage_const_70 
 _st_.inline(_sage_const_1 , latex(_sage_const_3 **_sage_const_2 ))
except:
 _st_.goboom(_sage_const_70 )
try:
 _st_.current_tex_line = _sage_const_70 
 _st_.inline(_sage_const_2 , latex((y-_sage_const_2 )**_sage_const_2 ))
except:
 _st_.goboom(_sage_const_70 )
try:
 _st_.current_tex_line = _sage_const_70 
 _st_.inline(_sage_const_3 , latex(sqrt(_sage_const_7 )**_sage_const_2 ))
except:
 _st_.goboom(_sage_const_70 )
try:
 _st_.current_tex_line = _sage_const_80 
 _st_.inline(_sage_const_4 , latex((x-_sage_const_0 )**_sage_const_2 ))
except:
 _st_.goboom(_sage_const_80 )
try:
 _st_.current_tex_line = _sage_const_80 
 _st_.inline(_sage_const_5 , latex(_sage_const_3 **_sage_const_2 ))
except:
 _st_.goboom(_sage_const_80 )
try:
 _st_.current_tex_line = _sage_const_80 
 _st_.inline(_sage_const_6 , latex((y-_sage_const_2 )**_sage_const_2 ))
except:
 _st_.goboom(_sage_const_80 )
try:
 _st_.current_tex_line = _sage_const_80 
 _st_.inline(_sage_const_7 , latex(sqrt(_sage_const_7 )**_sage_const_2 ))
except:
 _st_.goboom(_sage_const_80 )
try:
 _st_.current_tex_line = _sage_const_90 
 _st_.inline(_sage_const_8 , latex((x-_sage_const_0 )**_sage_const_2 ))
except:
 _st_.goboom(_sage_const_90 )
try:
 _st_.current_tex_line = _sage_const_90 
 _st_.inline(_sage_const_9 , latex(_sage_const_3 **_sage_const_2 ))
except:
 _st_.goboom(_sage_const_90 )
try:
 _st_.current_tex_line = _sage_const_90 
 _st_.inline(_sage_const_10 , latex((y-_sage_const_2 )**_sage_const_2 ))
except:
 _st_.goboom(_sage_const_90 )
try:
 _st_.current_tex_line = _sage_const_90 
 _st_.inline(_sage_const_11 , latex(sqrt(_sage_const_7 )**_sage_const_2 ))
except:
 _st_.goboom(_sage_const_90 )
try:
 _st_.current_tex_line = _sage_const_100 
 _st_.inline(_sage_const_12 , latex((x-_sage_const_0 )**_sage_const_2 ))
except:
 _st_.goboom(_sage_const_100 )
try:
 _st_.current_tex_line = _sage_const_100 
 _st_.inline(_sage_const_13 , latex(_sage_const_3 **_sage_const_2 ))
except:
 _st_.goboom(_sage_const_100 )
try:
 _st_.current_tex_line = _sage_const_100 
 _st_.inline(_sage_const_14 , latex((y-_sage_const_2 )**_sage_const_2 ))
except:
 _st_.goboom(_sage_const_100 )
try:
 _st_.current_tex_line = _sage_const_100 
 _st_.inline(_sage_const_15 , latex(sqrt(_sage_const_7 )**_sage_const_2 ))
except:
 _st_.goboom(_sage_const_100 )
_st_.endofdoc()

